# This playbook contains common/base plays for all nodes
# Looping with lists
# As it is a common task you can execute this from: ansible-playbook -i inventory/hosts_vm site.yml
---
  - name: Install base packages
    yum:
      name: "{{ item }}"
      state: present
    loop: "{{ base_packages }}"

  - name: Start the firewalld service
    service:
      name: firewalld
      state: started
      enabled:  yes
