# USING JINJA AND TEMPLATES.
# LOOPING IN TEMPLATES WITH VARIABLE LISTS.
# This is a simple task to test verifying if the required packages are defined or not by using Jinja2 template.
# Hint: Check on the group_vars & host_vars as it's related to the output of this task.
# To create a file --> $ ansible-playbook -i ./inventory/hosts_groups 2-12-tasks.yml --tags create
# To delete a created file --> $ ansible-playbook -i ./inventory/hosts_groups 2-12-tasks.yml --tags delete
---
  - hosts: all
    vars:
      packages: [git,vim,ruby]
    tasks:
      - name: Deploy a template file with a loop.
        template:
          src: templates/2-12-template.j2
          dest: /tmp/2-12-template.txt
        tags:
          - create
      - name: Remove the templated file.
        file:
          dest: /tmp/2-12-template.txt
          state: absent
        tags:
          - delete
