# SPECIFYING VARIABLES VIA INVENTORY
# Example to run a cmd:
# To create a file --> $ ansible-playbook -i ./inventory/2-5-host_groups 2-5-tasks.yml -e file_state=touch
# To delete a created file --> $ ansible-playbook -i ./inventory/2-5-host_groups 2-5-tasks.yml -e file_state=absent
---
  - hosts: web
    tasks:
      - name: Create a web file.
        file:
          dest: '{{web_file}}'
          state: '{{file_state}}'

  - hosts: backup
    tasks:
      - name: Create a backup file.
        file:
          dest: '{{backup_file}}'
          state: '{{file_state}}'

  - hosts: db
    tasks:
      - name: Create a db file.
        file:
          dest: '{{db_file}}'
          state: '{{file_state}}'
        when: db_file is defined

  - hosts: all
    tasks:
      - name: Create a file in all target machines.
        file:
          dest: '{{all_file}}'
          state: '{{file_state}}'
